### ISSUE TITLE
SyntaxError: Named export 'css' not found. (from esm import)

### ISSUE THREAD

**Issue by btakita** [cristianbote/goober#407]
`import 'solid-styled-components'` causes the following error from goober:

```
import { css, setup as gooberSetup } from "goober";
         ^^^
SyntaxError: Named export 'css' not found. The requested module 'goober' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'goober';
const { css, setup: gooberSetup } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:181:5)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async Module.run (file:///home/brian/work/ctx-core/ctx-core/node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/run/index.mjs:10:3)
    at async /home/brian/work/ctx-core/ctx-core/node_modules/.pnpm/uvu@0.5.2/node_modules/uvu/bin.js:26:5
 ELIFECYCLE  Command failed with exit code 1.
 ELIFECYCLE  Test failed. See above for more details.
```

See https://github.com/solidjs/solid-styled-components/issues/10

**Comment by rschristian** [comment]
Just ran into this myself.

The issue is that Goober is using `.js` as the `"import"` condition's extension without the package being labeled a module. This just isn't valid in Node. Need to use `.mjs` (which seems to have been decided against in #242) or add `"type": "module"`.

I'll see if I can get a PR together.

**Comment by cristianbote** [comment]
Just published `2.1.2` with @rschristian's fix. Let me know if you are still running into this. Thank you both for your excellent help!

**Comment by btakita** [comment]
Thank you for the PR & release. I'm now having issues with:

```ts
import { createGlobalStyles } from 'goober/global'
```

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and '/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/goober@2.1.3/node_modules/goober/global/package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
    at file:///home/work/project/node_modules/.pnpm/goober@2.1.3/node_modules/goober/global/dist/goober-global.cjs.js:1:7
    at ModuleWrap.evaluate (<anonymous>)
    at ModuleJob.run (node:internal/modules/esm/module_job:195:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:337:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:437:15)
    at async nodeImport (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/vite@2.7.10/node_modules/vite/dist/node/chunks/dep-76613303.js:60152:21)
    at async eval (/@fs/home/brian/work/portfoliome/censible-core/libs/ui-solid/src/company/Layout_companies.tsx:18:31)
    at async instantiateModule (/home/brian/work/portfoliome/censible-core/node_modules/.pnpm/vite@2.7.10/node_modules/vite/dist/node/chunks/dep-76613303.js:60094:9)
```

**Comment by rschristian** [comment]
Ah, sorry. Apparently Microbundle isn't ran from root, but installed separately for building the packages. Didn't catch that.

Need to upgrade them all in order to handle `.cjs` properly. I'll get a fix together soon.

**Comment by rschristian** [comment]
@btakita v2.1.5 was just published which should correct this.

**Comment by btakita** [comment]
@rschristian Thank you. I'm also getting successful builds.
